Testing, lockfile + package changes, some component modifications
diegobajetti/check-my-attendance pull request #7
Opened 2023-07-23 19:58 UTC by yasssami

2023-07-23 20:11 UTC, diegobajetti requested changes

2023-07-23 20:11 UTC, diegobajetti commented on src/components/Canvas.js
>  				},
Change to:
```suggestion
                video: true,
```

2023-07-23 20:23 UTC, diegobajetti approved these changes

2023-07-24 01:48 UTC, csong202 approved these changes

2023-07-24 03:37 UTC, merged